spring:
  mvc:
    static-path-pattern: '/static/**'
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      show-sql: true

toss:
  secret: <toss-secret>

ncp:
  api:
    client-id: <client-id>
    client-secret: <client-secret>

    api-access: <access-key>2
    api-secret: <secret-key>