spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  logging:
    level:
      org:
        thymeleaf: DEBUG
  profiles:
    active: git
